name: Build JAR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:28.3.3-dind
        options: --privileged

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Set up Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Build
        run: ./gradlew clean build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pjskilltrack-app
          path: |
            build/libs/*.jar
